### ISSUE TITLE
[Help wanted] Care to clarify what would be the correct usage for tag groups?

### ISSUE THREAD

**Issue by jpmurray** [rtconner/laravel-tagging#110]
Hello there!

I'm really glad to see group support for the package! But I do have some difficulty grasping what would be correct usage for groups.

Currently, I'm attaching tags to some model in a very straightforward way (in this example, I'm storing an article tags):

```
if (!empty($request->tags)) {
            $article->tag(explode(', ', $request->tags));
        }
```

And I would of course use `retag` to article update. Now, of I wanted to have different group of tags, let's say for an `articles` model, and for a `news` model. I would go on and create the corresponding groups from the artisan command then... What?

I get that I can easily get the tag in a group (`Tag::inGroup('MyTagGroup')->get()`) but how should I add a tag to an article, or a news? What is clear is that I should get the tags from the group to suggest to the user, then it would be a no brainer (get the correct tags, send them to the user, then when you save, it's the good ones?), but what if they enter a tag that isn't already created?

Do I really have to get all the tags in the request (like in the use case earlier), check for all of them if they are in the right group, create manually each tags that aren't, then associate tags? It seems a bit counter intuitive, no?

Could we see a, for example, `tag()` method that accepts a single or multiple tags as first parameters, and a group as second, so we would make sure the asked for tags are the one set for the wanted group, and that new ones are created in the right group?

Or do it already exists? Or am I misunderstanding the wanted usage for groups?

**Comment by unitedworx** [comment]
Have the same questions, how do we use tag groups when tagging or retaging a model making sure any tags used are part of a specific group? @jbardnz care to clarify?

Checking the source code I think we are missing the following methods to properly utilise groups.

`
$article->tagWithGroup('Gardening','MyGroup');
$article->untagWithGroup('Cooking','MyGroup'); 
$article->retagWithGoup(array('Fruit', 'Fish'), 'MyGroup'); 
Article::withAnyTagInGroup(['Gardening','Cooking'],'MyGroup')->get(); 
`

**Comment by jbardnz** [comment]
Hey guys,

Yeah just looking at this now it seems we would need those functions. My use case was slightly different in that I never needed to tag something on the fly - I already had my tags set in groups and they don't change. 

These functions should be easy to add - all of the underlying helper functions should already exist. I have been really slack at contributing to this package since I added support for Groups so happy to help with this one. 

Also wondering if we should add some default option if you create a new tag it can automatically be inserted into a group if one wasn't provided?

**Comment by unitedworx** [comment]
I suppose even the initial functions tag, retag, untang, withAnyTag, could be extended to accept a 2nd argument for the group if they only accept a single argument at the moment. I don't think a default is needed since anyone not wanting groups they will simply completely avoid them.

The way you have built it does it allow caving tags with exactly the same name but different slug? 

Let me know if you plan on working on this or I will have a go since I will be using it these next couple of days.

**Comment by rtconner** [comment]
@ jbardnz if you doing more work, feel free to add yourself to the credits in the readme if you wanted.

**Comment by jbardnz** [comment]
Hey guys,

I have started this work in the feature/group-updates branch. I need to clarify exactly what functionality is expected from each of these functions, I will add my thoughts here - let me know if anything is wrong:

`$article->tagWithGroup('Gardening','MyGroup');`
Tags the article with 'Gardening', the 'Gardening' tag gets added to the 'MyGroup' group.
Questions on this:
- What if the 'Gardening' tag was already in the group 'OtherGroup', would this override the current group?

`$article->untagWithGroup('Cooking','MyGroup');`
Is this meant to only untag 'Cooking' if it is in 'MyGroup'? So if 'Cooking' was in 'OtherGroup' this would result in no change.

`Article::withAnyTagInGroup(['Gardening','Cooking'],'MyGroup')->get();`
So this would find any articles tagged with 'Gardening' or 'Cooking' if those tags are in 'MyGroup'?
So if 'Cooking' is in 'OtherGroup' then this would only find articles tagged with 'Gardening'?

**Comment by unitedworx** [comment]
its inevitable to Have tags with the same name is multiple groups! so any operations involving groups should restrict to those groups. e.g. add that tag and associate it to that group, regardless if it exists in another group. when you untag a tag in a group then only untag limiting to that group as well, of if the same tag exist is in another group it wont touch it! The same for searching with withAnyTagInGroup it should fetch only items with matching tags that are in that group. 

btw I think it might be a better idea to extend the existing functions rather than creating new ones, you will introduce alot of duplicate code if you replicate the functions with different names! so basically if the second part is there do what is needed to limit to that group.

**Comment by jbardnz** [comment]
Yeah I think this is were their is some confusion. Currently the library doesn't allow for multiple tags (even within different groups).

The obvious answer is to allow multiple tags with the same name (within different groups). The tricky part of this is currently all the unique database indexes are based on the tag_slug - so to allow this we would need fairly major database changes. Potentially we could replace it with a compound index on tag_group_id + tag_slug but that could have a performance impact. 

Potentially we need to consider normalizing the database as requested in #94 and release a major version change. 


Also when writing the code I came to the same conclusion as you and have implemented this as an extension of the current functions :)

**Comment by vool** [comment]
Hi kinda confused on the tag groups too, my use is pretty similar to the [original tag issue](https://github.com/rtconner/laravel-tagging/issues/95#issue-136428343) (sets of tags "colors" and "sizes" associated to a model. 

The UI would have two different text areas one for each what would be the best way to work this with groups ?

**Comment by yasu** [comment]
👍

**Comment by chrisjohnstone** [comment]
I tried to make a pull request (my first ever) on the feature/group-updates branch (#132) which I think helps when removing tags. However, the tests for this fail with '--realpath option does not exist'. I'm not sure I understand what this is. Could anyone point me in the right direction.

Thanks for the work on this branch, it's really useful so far.

**Comment by 06chaynes** [comment]
@jbardnz Did you get this functionality working on your branch? I was about to start writing this functionality out myself but I thought I'd check with you first, see where you left off.

**Comment by michaelthuren** [comment]
Hi @jbardnz,

Any idea of when the withAnyTagInGroup will be implemented? :)

**Comment by jbardnz** [comment]
Hey guys,

As I said in my previous comment above, I don't think this functionality is possible without rewriting this package and normalizing the data as talked about in #94. I have no plans to make these changes myself but can give some guidance if anyone else is planning to do so.

Thanks

**Comment by rtconner** [comment]
This is several layers of relations. Very hard to implement in a query. We could change Tag Groups to relate to the `Tagged` model instead of the `Tag` model to make this relation less complicated. 

Group -> Tag -> Tagged -> Post is hard as it stands.

**Comment by rtconner** [comment]
As I asked in the other thread, does anyone use `count` field. That field is the biggest reason for these multiple tables.

**Comment by Xoshbin** [comment]
The `count` table is one of the reasons I'm using this library instead of https://github.com/spatie/laravel-tags because this library instead of duplicating every word in the database it counts them, But the other libraries are duplicating the words and it will be messy by the time.

**Comment by rtconner** [comment]
Leaving multiple tables.
